name: Test package

on: [push, pull_request]

jobs:
  build-and-test:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']
        laravel: ['12.*']
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 12.*
            stability: prefer-lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, pcov
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:^10.0" "nunomaduro/collision:^8.0" --dev --no-interaction --no-update --ansi
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ansi

      - name: Execute tests
        run: composer test:coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: .coverage/clover.xml
          verbose: true
